### PR TITLE
Addition of the api_stability_and_maturity.md contents

### PR DESCRIPTION
**Pull request by jbuberel**
With link from the top-level README.md from the "Good Citizen" section.

### CODE REVIEW

**Comment by matttproud** [comment]
Looks good.  Would you be OK doing an `git rebase` to [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) these commits into one?  :)

**Comment by jbuberel** [comment]
I seem to have gotten my fork into some wonky state after attempting the
rebase. Perhaps another day!

**Comment by matttproud** [comment]
I'll take a look at recovering it on Sunday, so no wastage of effort.
Jason Buberel notifications@github.com schrieb am Fr., 3. Juli 2015 um
16:00:

**Comment by jbuberel** [comment]
Just tested with:

> git rebase --interactive 2d73fa57d8ea9560bfa08edbce9ba72c3dd83b44
> Successfully rebased and updated refs/heads/master.

Which should mean my master/head is now fully rebased. Will open a new pull request to test.

**Pull request closed without merging**
